vim.list_extend(lvim.lsp.automatic_configuration.skipped_servers, { "jdtls", "pyright", "gopls" })

require("user.plugins")
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.lsp")
require("user.neoscroll")
require("user.fidget")
require("user.harpoon")
require("user.surround")
require("user.spectre")
require("user.hop")
require("user.whichkey")
require("user.treesitter")
require("user.telescopesetup")
require("user.telescope")
require("user.cmp")
require("user.dap")
