require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.lsp.general")
require("user.lsp.go")
require("user.lsp.nulls")
require("user.surround")
require("user.whichkey")
require("user.treesitter")
require("user.cmp")
require("user.dap")
require("user.telescope")
require("user.telescopefinders")
require("user.neotest")
require("user.nvim-colorizer")
require("user.swenv")
require("user.pythonpath")
require("user.commands")
require("user.simple-diagnostics")
require("user.trouble")
require("user.lualine")
require("user.dial")

vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
