lvim.leader = "space"
lvim.keys.command_mode["<C-a>"] = "<Home>"
lvim.keys.command_mode["<C-BS>"] = "<C-W>"
lvim.keys.command_mode["<C-e>"] = "<End>"
lvim.keys.command_mode["<C-v>"] = "<C-r>0"
lvim.keys.command_mode["<M-BS>"] = "<C-W>"
lvim.keys.command_mode["<M-Left>"] = "<S-Left>"
lvim.keys.command_mode["<M-Right>"] = "<S-Right>"
lvim.keys.insert_mode["<C-a>"] = "<home>"
lvim.keys.insert_mode["<C-e>"] = "<end>"
lvim.keys.insert_mode["<C-v>"] = "<esc>pa"
lvim.keys.normal_mode["<"] = "]"
lvim.keys.normal_mode["<A-a>"] = "<C-a>"
lvim.keys.normal_mode["<A-x>"] = "<C-x>"
lvim.keys.normal_mode["<C-Down>"] = "<C-W>j"
lvim.keys.normal_mode["<C-g>"] = ":LazyGit<CR>"
lvim.keys.normal_mode["<C-f>"] = ':lua require("telescope.builtin").current_buffer_fuzzy_find()<CR>'
lvim.keys.normal_mode["<C-j>"] = ':lua require("telescope.builtin").jumplist()<CR>'
lvim.keys.normal_mode["<C-Left>"] = "<C-W>h"
lvim.keys.normal_mode["<C-p>"] = ":Telescope projects<CR>"
lvim.keys.normal_mode["<C-Right>"] = "<C-W>l"
lvim.keys.normal_mode["<C-Up>"] = "<C-W>k"
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
lvim.keys.normal_mode["<M-Left>"] = ":bprev<CR>"
lvim.keys.normal_mode["<M-Right>"] = ":bnext<CR>"
lvim.keys.normal_mode["<S-Down>"] = ":m .+1<CR>=="
lvim.keys.normal_mode["<S-Left>"] = ":tabprevious<CR>"
lvim.keys.normal_mode["<S-Right>"] = ":tabnext<CR>"
lvim.keys.normal_mode["<S-Up>"] = ":m .-2<CR>=="
lvim.keys.normal_mode[">"] = "["
lvim.keys.normal_mode["ä"] = "}"
lvim.keys.normal_mode["ö"] = "{"
lvim.keys.normal_mode["W"] = ":noautocmd w<CR>"
-- lvim.visual_mode["<A-a>"] = "<C-a>"
-- lvim.visual_mode["<A-x>"] = "<C-x>"
-- lvim.visual_mode["<S-Down>"] = ":m '>+1<CR>gv=gv"
-- lvim.visual_mode["<S-Up>"] = ":m '<-2<CR>gv=gv"
-- lvim.visual_mode["ä"] = "}"
-- lvim.visual_mode["c"] = '"_c'
-- lvim.visual_mode["c"] = '"_c'
-- lvim.visual_mode["ö"] = "{"
-- lvim.visual_mode["p"] = '"_dP'
-- lvim.visual_mode["s"] = '"zy:Telescope grep_string default_text=<C-r>z<cr>'
-- lvim.keys.visual_block_mode["<"] = "]"
-- lvim.keys.visual_block_mode[">"] = "["
-- lvim.keys.visual_block_mode["p"] = "pgvy"
